baseURL: https://www.ab24.de
theme: 
  - my-hugo-base
defaultContentLanguage: de
defaultContentLanguageInSubdir: false
disableHugoGeneratorInject: true
disableKinds: ["taxonomy","taxonomyTerm","rss"]

Languages:
  de:
    baseurl: https://www.ab24.de/
    langtag: de-DE
  at:
    baseURL: https://www.ab24.at/
    langtag: de-AT

